version: '3.8'
services:
  server:
    build: .
    container_name: IOTProject
    ports:
      - "8888:8888" #docker8888端口映射到ubuntu的8888
    environment:
      - DB_HOST=iot
      - DB_PORT=5432
      - DB_USER=postgres
      - DB_PASSWORD=123456
      - DB_NAME=iot
    depends_on:
      iot:
        condition: service_healthy
    networks:
      - iot-network
  iot:
    image: postgres:16
    environment:
      POSTGRES_DB: iot       # 数据库名
      POSTGRES_USER: postgres     # 数据库用户名
      POSTGRES_PASSWORD: 123456 # 数据库密码
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres -d iot" ]
      interval: 5s
      timeout: 5s
      retries: 5
    volumes:
      - ./data/postgres:/var/lib/postgresql/data  # 挂载数据库数据目录，持久化存储
networks:
  iot-network:
    driver: bridge